package com.idea.demo.bean;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Person implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    private java.lang.String name;
    private java.lang.Integer age;
    private java.lang.String sexy;

    public Person() {
    }

    public java.lang.String getName() {
        return this.name;
    }

    public void setName(java.lang.String name) {
        this.name = name;
    }

    public java.lang.Integer getAge() {
        return this.age;
    }

    public void setAge(java.lang.Integer age) {
        this.age = age;
    }

    public java.lang.String getSexy() {
        return this.sexy;
    }

    public void setSexy(java.lang.String sexy) {
        this.sexy = sexy;
    }

    public Person(java.lang.String name, java.lang.Integer age,
                  java.lang.String sexy) {
        this.name = name;
        this.age = age;
        this.sexy = sexy;
    }

}